dependencies {
  // openflexo dep
  implementation flexoFoundation()
  api flexoOntology()
  // external dep
  //implementation 'com.sun.xsom:xsom:20140925'
  implementation group: 'org.glassfish.jaxb', name: 'xsom', version: '4.0.0-M1' // cannot upgrade because compiled for Java11
  // testing dep
  testImplementation flexoFoundationTest()

  // Test resource center
  testRuntimeOnly project(':xml-ta-test-rc')
}
